### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by obbyK** [hazelcast/quarkus-hazelcast-client#39]
I can't seem to find the client documentation. Other quarkus extensions have a guides page but didn't find one for this. If it is available? Putting the URL in the readme would be helpful

**Comment by pivovarit** [comment]
We're working on getting the guide accessible from the Quarkus site. However, keep in mind that it won't include much more details that this README. 

The reason is simple, there's not that much on top of a standard Hazelcast Client here. The standard Hazelcast client knowledge/configuration applies
